CREATE DATABASE Bamazon;
USE Bamazon;
CREATE TABLE products(
	ITEMID INTEGER(10) AUTO_INCREMENT NOT NULL,
    PRODUCTNAME VARCHAR(50) NOT NULL,
    DEPARTMENTNAME VARCHAR(50) NOT NULL,
    PRICE DECIMAL(10) NOT NULL,
    STOCKQUANTITY INTEGER(10),
    PRIMARY KEY (ITEMID)
);

INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('NOODLES', 'CARBS', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('APPLES', 'PRODUCE', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('ORANGES', 'PRODUCE', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('BREAD', 'CARBS', 5, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('CANDY', 'SWEETS', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('WATER', 'BEVERAGES', 1, 5);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('SWISSCHEESE', 'DAIRY', 3, 6);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('MILK', 'DAIRY', 3, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('CHOCOLATEMILK', 'DAIRY', 2, 10);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('AMCHEESE', 'DAIRY', 2, 10);

CREATE TABLE DEPARTMENTS (
	DEPARTMENTID INT NOT NULL AUTO_INCREMENT,
	DEPARTMENTNAME VARCHAR(100) NOT NULL,
	OVERHEADCOST DECIMAL(10,2) NOT NULL,
	TOTALSALES DECIMAL(10,2),
	PRIMARY KEY(DEPARTMENTID)
);

CREATE DATABASE Bamazon;
USE Bamazon;
CREATE TABLE products(
	ITEMID INTEGER(10) AUTO_INCREMENT NOT NULL,
    PRODUCTNAME VARCHAR(50) NOT NULL,
    DEPARTMENTNAME VARCHAR(50) NOT NULL,
    PRICE DECIMAL(10) NOT NULL,
    STOCKQUANTITY INTEGER(10),
    PRIMARY KEY (ITEMID)
);

INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('NOODLES', 'CARBS', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('APPLES', 'PRODUCE', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('ORANGES', 'PRODUCE', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('BREAD', 'CARBS', 5, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('CANDY', 'SWEETS', 2, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('WATER', 'BEVERAGES', 1, 5);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('SWISSCHEESE', 'DAIRY', 3, 6);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('MILK', 'DAIRY', 3, 2);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('CHOCOLATEMILK', 'DAIRY', 2, 10);
INSERT INTO products(PRODUCTNAME,DEPARTMENTNAME,PRICE,STOCKQUANTITY) VALUES ('AMCHEESE', 'DAIRY', 2, 10);

CREATE TABLE DEPARTMENTS (
	DEPARTMENTID INT NOT NULL AUTO_INCREMENT,
	DEPARTMENTNAME VARCHAR(100) NOT NULL,
	OVERHEADCOST DECIMAL(10,2) NOT NULL,
	TOTALSALES DECIMAL(10,2),
	PRIMARY KEY(DEPARTMENTID)
);

INSERT INTO DEPARTMENTS(DEPARTMENTNAME, OVERHEADCOST, TOTALSALES) VALUES('CARBS', 100, 3000);
INSERT INTO DEPARTMENTS(DEPARTMENTNAME, OVERHEADCOST, TOTALSALES) VALUES('PRODUCE', 100, 4000);
INSERT INTO DEPARTMENTS(DEPARTMENTNAME, OVERHEADCOST, TOTALSALES) VALUES('SWEETS', 100, 5000);
INSERT INTO DEPARTMENTS(DEPARTMENTNAME, OVERHEADCOST, TOTALSALES) VALUES('DAIRY', 100, 6000);